### PR TITLE
When is next patch release ?

### PR DESCRIPTION
**Pull request by pine**
Hello. I'm using this library in my project, but I found this errors.

screen shot 2017-03-29 at 18 57 11

But it has already fixed: https://github.com/dlazaro66/QRCodeReaderView/commit/42f53856c17a7cc2b0fc4dd5d853e1f8a5ec5301
I want to use latest version from jcenter 😢 

Thank you!

### CODE REVIEW

**Comment by dlazaro66** [comment]
Thanks for the Reminder and the PR. Actually, I just published a `2.0.2` version on JCenter. Sorry, I'm not going to merge your PR since the only change is a version raise and I think is not enough reason to accept it, hope you understand it :)

Thanks for your time!

**Comment by pine** [comment]
Thank you!

**Comment by nazmulalam900** [comment]
By

**Comment by nazmulalam900** [comment]
By

**Pull request closed without merging**
