### PR TITLE
Fix example in readme

### PR DESCRIPTION
**Pull request by auchri**

### CODE REVIEW

**Comment by dlazaro66** [comment]
I'm sorry, but I decided I'll not merge this PR because it doesn't add any value to the project nor the codebase. The idea behind pull-requests is to improve the current codebase, add new features or solve bugs for example, but I don't consider that change a variable name in the Readme.md will improve anything.

**Comment by auchri** [comment]
It does improve the current codebase? lol 

A broken documentation is actually a bug so my PR "solve bugs ".

**Comment by auchri** [comment]
You maybe didn't notice that in the current example `qrCodeReaderView` and `mydecoderview` where used for the same thing. Of course one of the two didn't exist (at least before your commit https://github.com/dlazaro66/QRCodeReaderView/commit/20fac1fad12f00e5c80162e279635c17ba40bc4b)

**Comment by dlazaro66** [comment]
Hey @auchri first, I'm sorry for not merging your PR. 

Let me explain you my thoughts about it; IMHO, the README file shouldn't be a copy&paste full working example but a demo about how can you use the library. You have a full example using all the library capabilities on `samples` directory. It's true that there were two different variable names but I don't see that as a blocker for you to integrate the library in your project as you'll have your own code structure (maybe you're not going to call that field `myQrDecoderView` , right?).

Anyway, I'm sorry if you have the sensation I was not aware of that and I "copied" your commit. As you can see here, other people pointed that before and I gave them the same response: https://github.com/dlazaro66/QRCodeReaderView/pull/104 https://github.com/dlazaro66/QRCodeReaderView/pull/91

It's my fault I forgot to do it before (maybe open an issue would have been great). This time, I needed to modify the Readme and release a new version, and as you also pointed this as a problem too, I decided to change that variable name in the commit you mention. 
In my opinion, as said, this slight readme modification is not enough reason to make a PR as, again imo, it doesn't add value to the codebase. 

Finally, if you think you deserve the recognition of this work or this commit and appear on the contributor's list of the project just say it; I'd revert my commit and reopen this PR in order to be merged.

Sorry for the inconveniences again, and thanks for your time.

**Pull request closed without merging**
