### PR TITLE
Fix camera sensor rotation/Position

### PR DESCRIPTION
**Pull request by vlntdds**
Problem: Some devices like LG Nexus 5x and Samsung Galaxy Tab 2 Lite the
preview image appears mirrored and upsided down.

Solution: Added setCameraDisplayOrientation to fix the camera sensor
rotation on some devices.

I've surrounded the setCameraDisplayOrientation with check for API>9.

### CODE REVIEW

**Comment by dlazaro66** [comment]
I really appreciate this contribution! Sorry for the delay, I'm merging this right now and uploading a new version to jcenter asap, also adding you as a contributor :)

Thank you so much!

**Comment by yueban** [comment]
@dlazaro66 didn't see a new version on [bintray](https://bintray.com/dlazaro66/maven/QRCodeReaderView/view#release)

**Comment by dlazaro66** [comment]
@yueban we're doing several changes on the library in our free time, and we'll upload a new version. Meanwhile, I recommend you to download the dependency via jitpack.io

**Comment by yueban** [comment]
@dlazaro66 ok, thanks for reply

**Pull request merged**
